# Generated by Django 5.2.10 on 2026-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifemanager', '0002_goalstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='media_url',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='diary_media/'),
        ),
    ]
