# Generated by Django 5.2.10 on 2026-01-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifemanager', '0003_remove_diaryentry_media_url_diaryentry_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sphere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifemanager.lifesphere'),
        ),
    ]
