# Generated by Django 6.0.1 on 2026-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifemanager', '0004_reminder_sphere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-is_pinned', 'deadline']},
        ),
        migrations.AddField(
            model_name='goal',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
