# Generated by Django 6.0.1 on 2026-01-17 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifemanager', '0006_goal_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='Текст пункта')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lifemanager.note')),
            ],
            options={
                'verbose_name': 'Пункт заметки',
                'verbose_name_plural': 'Пункты заметок',
            },
        ),
    ]
